# -*- coding: utf-8 -*-

# variables
BASELINE = 0
TREATMENTS_NAMES = {0: "Baseline"}

# parameters
DOTATION = 20
TAUX_INDIV = 1
TAUX_LOCAL = 0.5
TAUX_GLOBAL = 0.5
TREATMENT = BASELINE
TAUX_CONVERSION = 0.1
NOMBRE_PERIODES = 2
TAILLE_GROUPES = 4
TAILLE_SOUS_GROUPES = 2
GROUPES_CHAQUE_PERIODE = False
MONNAIE = u"ecu"
PERIODE_ESSAI = False

# DECISION
DECISION_MIN = 0
DECISION_MAX = DOTATION
DECISION_STEP = 1
